Collections:
  - Name: OFD
    Metadata:
      Training Data:
        - CIFAR-10
    Paper:
      URL: https://arxiv.org/abs/1904.01866
      Title: A Comprehensive Overhaul of Feature Distillation
    README: configs/distill/mmcls/ofd/README.md
    Code:
      URL: https://github.com/open-mmlab/mmrazor/blob/dev-1.x/mmrazor/models/algorithms/distill/configurable/overhaul_feature_distillation.py
      Version: v2.0.0
    Converted From:
      Code: https://github.com/clovaai/overhaul-distillation
Models:
  - Name: ofd_backbone_resnet50_resnet18_8xb16_cifar10
    In Collection: OFD
    Metadata:
      Location: backbone
      Student:
        Config: mmrazor::vanilla/mmcls/wide-resnet/wrn16_2_b16x8_cifar10.py
        Weights: TODO
        Metrics:
          Top 1 Accuracy: TODO
          Top 5 Accuracy: TODO
      Teacher:
        Config: mmrazor::vanilla/mmcls/wide-resnet/wrn28_4_b16x8_cifar10.py
        Weights: TODO
        Metrics:
          Top 1 Accuracy: 95.4400
          Top 5 Accuracy: 99.8200
    Results:
      - Task: Image Classification
        Dataset: CIFAR-10
        Metrics:
          Top 1 Accuracy: 95.4400
    Config: configs/distill/mmcls/ofd/ofd_backbone_resnet50_resnet18_8xb16_cifar10.py
    Weights: TODO
